"""initial schema

Revision ID: e6c007a09a72
Revises: 
Create Date: 2025-05-29 19:10:25.950453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c007a09a72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salles',
        sa.Column('id', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('nom', sa.String(), nullable=False),
        sa.Column('capacite', sa.Integer(), nullable=False),
        sa.Column('localisation', sa.String(), nullable=False),
        sa.Column('disponible', sa.Boolean(), nullable=True, default=True)
    )
    op.create_table('reservations',
        sa.Column('id', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('salle_id', sa.String(length=36), sa.ForeignKey('salles.id'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('heure', sa.Time(), nullable=False),
        sa.Column('utilisateur', sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('salles')
    # ### end Alembic commands ###
