name: Build
on:
  pull_request:
    branches:
      - main
      - develop
      - release/**
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Alembic migrations
        run: poetry run alembic upgrade head

      - name: Run tests with coverage
        run: |
          poetry run pip install pytest pytest-cov
          PYTHONPATH=. poetry run pytest --cov=app --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}